const Const = {
    HOME: `/`,
    SET_ARTICLES : 'SET_ARTICLES',
    SET_TOTAL_ARTICLES:'SET_TOTAL_ARTICLES',
    START_LOADING : 'START_LOADING',
    DONE_LOADING : 'DONE_LOADING',
    ACTION_FAILED : 'ACTION_FAILED'
  };
  
  export default Const;